---
title: "HIF1a mice transcriptomics in response to time of day exercise"
subtitle: "Differential expression visualisation"
author: "Kirstin MacGregor"
date: "`r paste('Project start: January 04, 2023.', 'Last update:', format(Sys.time(), '%B %d, %Y'))`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: true
knit: (function(input, ...) {
    rmarkdown::render(
      input,
      output_file = paste0(
        xfun::sans_ext(input), '-', Sys.Date(), '.html'
      ),
      envir = globalenv()
    )
  })
editor_options: 
  chunk_output_type: console
---
<style>
#TOC {
  background: url("https://medarbetare.ki.se/sites/default/files/styles/article_full_width/public/qbank/ki_logo_liggande_exempel.jpg?itok=JTRhQLNk");
  background-size: contain;
  padding-top: 100px !important;
  background-repeat: no-repeat;
}
</style>

# Set up
```{r setup, include=FALSE}
source(here::here("./R/functions.R"))
library(viridis)
library(DESeq2)

dir.create(here::here("./out"), showWarnings = FALSE)
dir.create(here::here("./out/volcano"), showWarnings = FALSE)
dir.create(here::here("./out/MA_plot"), showWarnings = FALSE)
dir.create(here::here("./out/upset"), showWarnings = FALSE)
```

# Load data
```{r}
DE_results <- readRDS(file=  here::here("../02_diff_exp/out/DE_results.rda"))
```

# Descriptive plots

## Main effects
```{r, warning= FALSE, message= FALSE}
main_effects_plot_dat <- do.call("rbind", DE_results$main_effects[2:4])
rownames(main_effects_plot_dat) <- NULL

main_effects_plot_dat <- main_effects_plot_dat |>
  dplyr::mutate(dir_cat = dplyr::case_when(
      FDR > 0.1 ~ "ns",
      FDR < 0.1 & logFC <= 0 ~ "down",
      FDR < 0.1 & logFC > 0 ~ "up",
      is.na(FDR) ~ "ns"
    ),
    dir_cat = factor(dir_cat, levels = c("up", "down", "ns"))
  ) |> 
  dplyr::ungroup()

# Volcano
volcano_main_effects <- volcano_fun(main_effects_plot_dat)

# Upset
main_effects_upset <- upset_plot_dat_fun(main_effects_plot_dat)
main_effects_upset <- upset_gg(main_effects_upset)
main_effects_upset <- main_effects_upset$upset

# Save
ggplot2::ggsave(filename= "volcano_main_effects.pdf", plot= volcano_main_effects, path= here::here("./out/volcano"), width= 10, height= 10)
ggplot2::ggsave(filename = "upset_main_effects.pdf", plot = main_effects_upset, path = here::here("./out/upset"), width= 6, height= 6)

# Tidy up 
rm(volcano_main_effects, main_effects_upset, main_effects_plot_dat)
```

# Exercise contrast
```{r, warning= FALSE, message= FALSE}
ex_plot_dat <- do.call("rbind", DE_results$ex_contrasts)
rownames(ex_plot_dat) <- NULL

ex_plot_dat <- ex_plot_dat |>
  dplyr::mutate(
    comp = dplyr::case_when(
      comp == "zt3_wt" ~ "ZT3-WT",
      comp == "zt15_wt" ~ "ZT15-WT",
      comp == "zt3_ko" ~ "ZT3-KO",
      comp == "zt15_ko" ~ "ZT15-KO"
    ),
    comp = factor(comp, levels = c("ZT3-WT", "ZT3-KO", "ZT15-WT", "ZT15-KO")),
    dir_cat = dplyr::case_when(
      FDR > 0.1 ~ "ns",
      FDR < 0.1 & logFC <= 0 ~ "down",
      FDR < 0.1 & logFC > 0 ~ "up",
      is.na(FDR) ~ "ns"
    ),
    dir_cat = factor(dir_cat, levels = c("up", "down", "ns"))
  )

# Volcano
volcano_ex <- volcano_fun(ex_plot_dat)

# Upset plot 
ex_contrasts_upset <- upset_plot_dat_fun(ex_plot_dat) #arrange data as list
ex_contrasts_upset <- upset_gg(ex_contrasts_upset)
ex_contrasts_upset <- ex_contrasts_upset$upset

# Save
ggplot2::ggsave(filename= "volcano_sed_vs_ex.pdf", plot= volcano_ex, path= here::here("./out/volcano"), width= 7, height= 7)
ggplot2::ggsave(filename= "upset_sed_vs_ex.pdf", plot= ex_contrasts_upset, path = here::here("./out/upset"), width= 7, height= 7)

# Tidy up 
rm(ex_plot_dat, volcano_ex, ex_contrasts_upset)
```

## Genotype contrast
```{r, warning= FALSE, message= FALSE}
genotype_plot_dat <- do.call("rbind", DE_results$genotype_contrasts)
rownames(genotype_plot_dat) <- NULL

genotype_plot_dat <- genotype_plot_dat |>
  dplyr::mutate(
    comp = dplyr::case_when(
      comp == "zt3_ex" ~ "ZT3-ex",
      comp == "zt15_ex" ~ "ZT15-ex",
      comp == "zt3_sed" ~ "ZT3-sed",
      comp == "zt15_sed" ~ "ZT15-sed"
    ),
    comp = factor(comp, levels = c("ZT3-sed", "ZT3-ex", "ZT15-sed", "ZT15-ex")),
    dir_cat = dplyr::case_when(
      FDR > 0.1 ~ "ns",
      FDR < 0.1 & logFC <= 0 ~ "down",
      FDR < 0.1 & logFC > 0 ~ "up",
      is.na(FDR) ~ "ns"
    ),
    dir_cat = factor(dir_cat, levels = c("up", "down", "ns"))
  )

##volcano
volcano_genotype <- volcano_fun(genotype_plot_dat)

##upset plot 
genotype_contrasts_upset <- upset_plot_dat_fun(data = genotype_plot_dat) #arrange data as list
genotype_contrasts_upset <- upset_gg(genotype_contrasts_upset)
genotype_contrasts_upset <- genotype_contrasts_upset$upset

##save results
ggplot2::ggsave(filename = "volcano_wt_vs_ko.pdf", plot = volcano_genotype, path = here::here("./out/volcano"), width= 7, height= 6)
ggplot2::ggsave(filename= "upset_wt_vs_ko.pdf", plot = genotype_contrasts_upset, path = here::here("./out/upset"), width= 7, height= 6)

# Tidy up
rm(genotype_plot_dat, volcano_genotype, genotype_contrasts_upset)
```

## Heatmap
```{r}
temp_dat <- rbind(DE_results$zt_contrasts$wt_sed,
                  DE_results$zt_contrasts$wt_ex,
                  DE_results$zt_contrasts$ko_sed,
                  DE_results$zt_contrasts$ko_ex
                  ) |> 
  dplyr::mutate(comp = dplyr::case_when(
    comp == "wt_sed" ~ "WT-sed",
    comp == "wt_ex" ~ "WT-ex",
    comp == "ko_sed" ~ "KO-sed",
    comp == "ko_ex" ~ "KO-ex"
  ),
  comp = factor(comp, levels= c( "WT-sed", "KO-sed", "WT-ex", "KO-ex")))
    
    
# Get sig sites
sig_sites <- temp_dat |> 
  dplyr::filter(FDR < 0.1)  |> 
  dplyr::select(gene_id) |> 
  dplyr::distinct(gene_id)


## arrange data in wide format
temp_dat <- temp_dat |> 
  dplyr::mutate(N= 1:nrow(temp_dat)) |> 
  dplyr::filter(gene_id %in% sig_sites$gene_id) |> 
  dplyr::select(c(logFC, comp, gene_id, N)) |> 
  tidyr::pivot_wider(id_cols=!c(N), values_from = "logFC", names_from = "comp") |> 
  tibble::column_to_rownames(var = "gene_id") |> 
  dplyr::select(c("WT-sed", "KO-sed", "WT-ex", "KO-ex")) |> 
  as.matrix() 

temp_dat <- scale(t(temp_dat))
# Make annotation
comp <- c(
  "WT-sed",
  "KO-sed",
  "WT-ex",
  "KO-ex"
)
  
genotype <- c(
  "WT",
  "KO",
  "WT",
  "KO"
)
treatment <- c(
  "sedentary",
  "sedentary",
  "exercise",
  "exercise"
)
meta_dat_hm <- data.frame(comp, genotype, treatment)

hm_annot_comps <- ComplexHeatmap::HeatmapAnnotation(
  df = meta_dat_hm[, c("genotype", "treatment")],
  col = list(
    genotype = c("WT" = "darkgreen", "KO" = "lightgreen"),
    treatment = c("sedentary" = "grey69", "exercise" = "grey35")
  )
)

#make heatmap
hm <-
ComplexHeatmap::Heatmap(
  t(temp_dat),
  name = "scaled logFC",
  show_row_name = FALSE,
  show_column_names = TRUE,
  column_names_rot  = 0,
  column_names_centered = TRUE,
  cluster_rows = TRUE,
  cluster_columns = FALSE,
  col=viridis::cividis(100),
  width= unit(7, "cm"),
  top_annotation = hm_annot_comps
)

# Save
pdf(here::here("./out/genotype_heatmap.pdf"), width=6, height=6)
hm
dev.off()

# Tidy
rm(sig_sites, hm_annot_comps, hm, meta_dat_hm, genotype, comp, treatment, temp_dat)
```

# ZT contrast
```{r, warning= FALSE, message= FALSE}
zt_plot_dat <- do.call("rbind", DE_results$zt_contrasts)
rownames(zt_plot_dat) <- NULL

zt_plot_dat <- zt_plot_dat |>
  dplyr::mutate(
    comp = dplyr::case_when(
      comp == "wt_sed" ~ "WT-sed",
      comp == "wt_ex" ~ "WT-ex",
      comp == "ko_sed" ~ "KO-sed",
      comp == "ko_ex" ~ "KO-ex"
    ),
    comp = factor(comp, levels = c("WT-sed", "KO-sed", "WT-ex", "KO-ex")),
    dir_cat = dplyr::case_when(
      FDR > 0.1 ~ "ns",
      FDR < 0.1 & logFC <= 0 ~ "down",
      FDR < 0.1 & logFC > 0 ~ "up",
      is.na(FDR) ~ "ns"
    ),
    dir_cat = factor(dir_cat, levels = c("up", "down", "ns"))
  ) |> 
  dplyr::ungroup()

# Volcano
volcano_zt <- volcano_fun(zt_plot_dat)

# Upset plot 
zt_contrasts_upset <- upset_plot_dat_fun(zt_plot_dat) #arrange data as list
zt_contrasts_upset <- upset_gg(zt_contrasts_upset)
zt_contrasts_upset <- zt_contrasts_upset$upset
zt_contrasts_upset

# Save
ggplot2::ggsave(filename = "volcano_zt3_vs_zt15.pdf", plot = volcano_zt, path = here::here("./out/volcano"), width= 7, height= 6)
ggplot2::ggsave(filename = "upset_zt3_vs_zt15.pdf", plot = zt_contrasts_upset, path = here::here("./out/upset"), width= 7, height= 7)

#cleanup 
rm(volcano_zt, zt_contrasts_upset, zt_plot_dat)
```

# Session info
```{r}
sessionInfo()
```